name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore --no-cache

      - name: Build and publish with base path
        run: dotnet publish -c Release -p:PublishTrimmed=false -p:BlazorWebAssemblyLoadAllGlobalizationData=true -p:BasePath=/blazorapp/ -o build

      - name: Add .nojekyll file to prevent GitHub Pages processing
        run: echo > build/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/wwwroot
