name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Cambia si usas otra versión

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and publish
        run: dotnet publish -c Release -o build

      - name: Fix base href
        run: sed -i 's|<base href="/" />|<base href="/blazorapp/" />|' build/wwwroot/index.html

      - name: Add .nojekyll file
        run: echo > build/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/wwwroot
